### ISSUE TITLE
# operator should return notIn

### ISSUE THREAD

**Issue by ieow** [alexsuslov/wc-query-sequelize#1]
Currently it # return $nin instead of $notIn 
      const resp = query({ name: '#1|2|3' });
      assert.equal( 1, resp.where.name.$nin[0]);

from latest sequalize V3
$between: [6, 10],     // BETWEEN 6 AND 10
$notBetween: [11, 15], // NOT BETWEEN 11 AND 15
$in: [1, 2],           // IN [1, 2]
$notIn: [1, 2],        // NOT IN [1, 2]
$like: '%hat',         // LIKE '%hat'
$notLike: '%hat'       // NOT LIKE '%hat'
$iLike: '%hat'         // ILIKE '%hat' (case insensitive) (PG only)

**Comment by alexsuslov** [comment]
thanks!
unbug $notIn.
